#!/bin/bash

if [[ $# != 2 || $S1 == "-h" || $S1 == "--help" ]]
then
        echo "Usage: "
        echo "  $0 user_name FQDN"
        exit 1
fi

user_name=$1
FQDN=$2
config_file=/etc/letsencrypt/$FQDN.cli.ini
script_dir=$(dirname "$0")

cd "$script_dir"
# Read config file with paths to WP-installs and usernames
source /usr/local/default/etc/wp-mass-admin/wpma.conf
if [ -e /usr/local/etc/wp-mass-admin/wpma.conf ]
then
    source /usr/local/etc/wp-mass-admin/wpma.conf
fi

# Create configfolder+file if letsencrypt hasn't run yet
mkdir -p /etc/letsencrypt
touch "$config_file"

# Create a config file for domain
cat > "$config_file" << EOF
# Use a 4096 bit RSA key instead of 2048
rsa-key-size = 4096

# Uncomment and update to register with the specified e-mail address
email = $admin_mail

# Uncomment and update to generate certificates for the specified
# domains.
domains = $FQDN

# Uncomment to use the webroot authenticator. Replace webroot-path with the
# path to the public_html / webroot folder being served by your web server.
authenticator = webroot
webroot-path = $basePath/$user_name/wordpress

EOF

# There's a bug in the letsencrypt client which forces us to create some folders
# for it in the webroot, and set root as owner, before we run the client.
# https://community.letsencrypt.org/t/webroot-plugin-the-client-lacks-sufficient-authorization/5479/2
mkdir -p "$basePath/$user_name/wordpress/.well-known/acme-challenge"
chown -R root "$basePath/$user_name/wordpress/.well-known"

# Run letsencrypt and get cert
../letsencrypt/letsencrypt-auto certonly --renew-by-default --config "$config_file"

