#!/bin/bash
set -e

if [[ $# != 2 ]]
then
		echo "Usage: "
		echo "	$0 user_name FQDN"
		exit 1
fi

user_name=$1
FQDN=$2
config_file=/etc/nginx/sites-available/$FQDN

script_dir=$(dirname "$0")
cd "$script_dir"
# Read config file with paths to WP-installs and usernames
source /usr/local/default/etc/wp-mass-admin/wpma.conf
if [[ -e /usr/local/etc/wp-mass-admin/wpma.conf ]]; then
    source /usr/local/etc/wp-mass-admin/wpma.conf
fi

if [[ $useHttps == "yes" ]]
then
	./use-https "$user_name" "$FQDN"
else
	./no-https "$user_name" "$FQDN"
fi
