#!/bin/bash
set -e

if [[ $# != 2 ]]
then
		echo "Usage: "
		echo "	$0 userName FQDN"
		exit 1
fi

userName=$1
FQDN=$2
configFile=/etc/nginx/sites-available/$FQDN

scriptDir=$(dirname "$0")
cd "$scriptDir"
# Read config file with paths to WP-installs and usernames
source /usr/local/default/etc/wp-mass-admin/wpma.conf
if [[ -e /usr/local/etc/wp-mass-admin/wpma.conf ]]; then
    source /usr/local/etc/wp-mass-admin/wpma.conf
fi

# Create logfolder
mkdir -p /var/log/nginx/"$FQDN"

# SSL conf
cat >> "$configFile" << EOF
server {
	listen 80;
	server_name $FQDN;

	error_log /var/log/nginx/$FQDN/error.log;
	access_log /var/log/nginx/$FQDN/access.log;

	root $basePath/$userName/wordpress;
	index index.php index.html index.htm;
    
    include includes/wpma-includes.conf;
    
	location ~ \.php$ {
		try_files \$uri =404;
		fastcgi_pass unix:/srv/$userName/socket/php-fpm.sock;
		fastcgi_index index.php;
		fastcgi_param	SCRIPT_FILENAME	\$document_root/\$fastcgi_script_name;
		include fastcgi_params;
	}
}

EOF

# If site is not enabled already, enable it
ln -sf "$configFile" /etc/nginx/sites-enabled
# Enable site by reloading
systemctl reload nginx
