#!/bin/bash
set -e

if [[ $# != 2 ]]
then
	echo "Usage: "
	echo "	$0 user_name"
	exit 1
fi

user_name=$1
FQDN=$2
config_file=/etc/php5/fpm/pool.d/$FQDN.conf

script_dir=$(dirname "$0")
cd "$script_dir"

# Read config file with paths to WP-installs and usernames
source /usr/local/default/etc/wp-mass-admin/wpma.conf
if [[ -e /usr/local/etc/wp-mass-admin/wpma.conf ]]; then
    source /usr/local/etc/wp-mass-admin/wpma.conf
fi

cat > "$config_file" << EOF
[$FQDN]
prefix = $base_path/$user_name
user = $user_name
group = $user_name
chroot = $prefix
chdir = wordpress

listen = socket/php-fpm.sock
listen.owner = $user_name
listen.group = www-data
listen.mode = 770

pm = ondemand
pm.max_children = 4

EOF

# Activate app pool
service php5-fpm restart
