#!/bin/bash
set -e

if [[ $# != 2 ]]
then
	echo "Usage: "
	echo "	$0 userName"
	exit 1
fi

userName=$1
FQDN=$2
configFile=/etc/php5/fpm/pool.d/$FQDN.conf

scriptDir=$(dirname "$0")
cd "$scriptDir"

# Read config file with paths to WP-installs and usernames
source /usr/local/default/etc/wp-mass-admin/wpma.conf
if [[ -e /usr/local/etc/wp-mass-admin/wpma.conf ]]; then
    source /usr/local/etc/wp-mass-admin/wpma.conf
fi

cat > "$configFile" << EOF
[$FQDN]
prefix = $basePath/$userName
user = $userName
group = $userName
chroot = $prefix
chdir = wordpress

listen = socket/php-fpm.sock
listen.owner = $userName
listen.group = www-data
listen.mode = 770

pm = ondemand
pm.max_children = 4

EOF

# Activate app pool
service php5-fpm restart
