#!/bin/bash
set -e

if [[ $# != 2 || $S1 == "-h" || $S1 == "--help" ]]
then
	echo "Usage: "
	echo "	$0 user_name fullURL"
	exit 1
fi

script_dir=$(dirname "$0")
cd "$script_dir"

# Read config file with paths to WP-installs and usernames
source /usr/local/default/etc/wp-mass-admin/wpma.conf

if [[ -e /usr/local/etc/wp-mass-admin/wpma.conf ]]; then
    source /usr/local/etc/wp-mass-admin/wpma.conf
else
    echo "Please add a conf file to your /usr/local/etc/wp-mass-admin folder. Instructions can be found in the README."
    exit 2
fi

user_name=$1
FQDN=$2
user_password=$(echo -n $RANDOM | md5sum | awk '{print $1}')
wp_admin_password=$(echo -n $RANDOM | md5sum | awk '{print $1}')
base_dir=$base_path/$user_name
install_dir=$base_dir/wordpress
socket_dir=$base_dir/socket
protocol="https://"

if [[ $useHttps == "yes" ]]
then
    protocol="https"
else
    protocol="http"
fi

# Append our user to the config
./write-conf "$user_name"

# Create user in Linux and MySQL
useradd -p "$(echo "$user_password" | openssl passwd -1 -stdin)" "$user_name"

echo "Please enter root password for MYSQL"
mysql --user=root -p -e "create database $user_name;
CREATE USER '$user_name'@localhost IDENTIFIED BY '$user_password';
GRANT ALL PRIVILEGES ON $user_name . * TO '$user_name'@'localhost';"
echo ""

# Create folders for WP. www-data in user group and correct permissions for server to run
mkdir -p "$install_dir"
mkdir -p "$socket_dir"
mkdir -p "$install_dir"/wp-content
chown -R "$user_name":www-data "$base_dir"
chmod -R 710 "$base_dir"
chmod -R 750 "$base_dir"/wp-content
chmod -R g+s "$base_dir"

echo "Installing Wordpress"
# Install Wordpress
su - "$user_name" -c "
cd '$install_dir'
wp core download --locale=sv_SE
echo \"define('WP_TEMP_DIR', '/srv/$user_name/wordpress/wp-content/tmp-upload');\" | wp core config --extra-php --dbname='$user_name' --dbuser=$user_name --dbpass='$user_password' --locale=sv_SE
wp core install --url='$protocol://$FQDN' --title='$user_name website' --admin_user='$adminUser' --admin_password='$wp_admin_password' --admin_email='$adminMail'"

# Installing AD plugin for Wordpress
if [[ $active_directory == "yes" ]]
then
	echo "Installing AD-plugin"
  su "$user_name" -c "cd $install_dir
  wp plugin install active-directory-integration
  wp plugin activate active-directory-integration"
fi
echo ""

# Create config files for nginx and uwsgi
./nginx "$user_name" "$FQDN"
./php5-fpm "$user_name" "$FQDN"

echo ""
echo "This is the password for MySQL- and system user $user_name:"
echo $user_password
echo ""

echo "This is the password for WP-administrator-user $adminUser:"
echo $wp_admin_password
echo ""
