#!/bin/bash

if [[ $# != 0 || $1 == "-h" || $1 == "--help" ]]
then
		echo "Usage: "
		echo "  $0"
		exit 1
fi

cd "$(dirname "$0")"

# Read config file with paths to WP-installs and usernames
source /usr/local/default/etc/wp-mass-admin/wpma.conf

if [[ -e /usr/local/etc/wp-mass-admin/wpma.conf ]]; then
    source /usr/local/etc/wp-mass-admin/wpma.conf
fi

for userName in $userNames
do
	echo "Checking install $userName for minor update..."
	cd "$basePath/$userName/wordpress"
	if wp core check-update --allow-root | grep "minor"
	then
		echo ""
		echo "Updating site for user $userName..."
		su - "$userName" -c "cd $basePath/$userName/wordpress
wp core update --version=$(wp core check-update --allow-root | grep minor | awk "{'print $1'}")
wp core update-db"
	else
		echo "No minor update found for WP site $userName"
		if wp core check-update --allow-root | grep "major"
		then
			echo ""
			echo "MAJOR UPDATE AVAILABLE FOR $userName"
		fi
	fi

	# Update all plugins as well
	echo "Updating plugins for $userName"
	su - "$userName" -c "cd $basePath/$userName/wordpress
wp plugin update --all"


	# Update all plugins as well
	echo "Updating themes for $userName"
	su - "$userName" -c "cd $basePath/$userName/wordpress
wp theme update --all"

	echo ""
done
